spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    name: mysql_ds
    url: jdbc:mysql://10.2.146.116:3306/market?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: etl
    password: etl123
    #druid相关配置
    druid:
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 6000
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 30000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validationQuery: SELECT 1
      #connectionProperties: config.decrypt=false # database connection plain password
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
server:
  port: 9007
