server:
  port: 8080

spring:
  application:
    name: market #你的应用/服务的名字可以采取网关分配的passId
  profiles:
    active: dev


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  # type-handlers-package: com.market.base.framework.demand.handler  #自定义字段映射
  global-config:
    db-config:
      field-strategy: NOT_NULL
      id-type: auto
      db-type: mysql
      logic-delete-value: 1     #逻辑删除
      logic-not-delete-value: 0    #逻辑删除
    banner: false
    super-mapper-class: com.market.base.framework.mapper.BaseMapper
    #type-enums-package: com.market.base.common.enums
  #type-aliases-package: com.tencent.goff.modules.datasource.model.entity

swagger:
  enable: true
