spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    name: mysql_ds
    url: jdbc:mysql://10.2.133.52:3306/market?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Root1234$
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 6000
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 30000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validationQuery: SELECT 1
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      useGlobalDataSourceStat: true
server:
  port: 9007
